namespace DeskCompanion.Services;

/// <summary>English. Keys are the Russian table's; a missing one falls back to Russian.</summary>
public static partial class Strings
{
    public static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        // ------------------------------------------------------------ menu
        ["nav_overview"] = "Overview",
        ["nav_screens"] = "Screens",
        ["nav_stats"] = "Statistics",
        ["nav_radar"] = "Radar",
        ["nav_computer"] = "Computer",
        ["nav_settings"] = "Settings",

        // ------------------------------------------------- device connection
        ["link_searching"] = "looking for the device",
        ["link_waiting"] = "waiting for the device",
        ["link_none"] = "no connection",
        ["link_ok"] = "device connected",
        ["tray_state"] = "Desk Companion — {0}",
        ["tray_air"] = "Desk Companion — CO₂ {0} ppm, {1}",
        ["tray_at_desk"] = "at the desk",
        ["tray_nobody"] = "nobody there",
        ["tray_open"] = "Open",
        ["tray_quit"] = "Quit",
        ["board_no_answer"] = "the device did not answer",
        ["board_timeout"] = "the device did not answer in time",
        ["board_no_host"] = "that address is not on the network",
        ["board_no_link"] = "cannot reach the device",
        ["board_status"] = "the device answered {0}",
        ["board_empty_file"] = "the device returned an empty file",
        ["not_saved"] = "not saved",

        // --------------------------------------------------------- overview
        ["overview_hint"] = "everything the device knows right now",
        ["card_air"] = "AIR",
        ["card_desk"] = "DESK",
        ["card_outside"] = "OUTSIDE",
        ["card_pc"] = "COMPUTER",
        ["card_board"] = "DEVICE",
        ["air_silent"] = "sensor is silent",
        ["air_caption"] = "{0:0.0} °C · humidity {1:0} %",
        ["desk_present"] = "here",
        ["desk_empty"] = "empty",
        ["radar_distance"] = "radar sees someone at {0} cm",
        ["radar_online"] = "radar connected",
        ["radar_silent"] = "radar is silent",
        ["weather_none"] = "no forecast",
        ["pc_no_window"] = "no active window",
        ["pc_offline"] = "the device gets no data from this computer — see the Computer page",
        ["pc_cpu"] = "processor",
        ["pc_cpu_temp"] = "its temperature",
        ["pc_gpu"] = "graphics card",
        ["pc_gpu_temp"] = "its temperature",
        ["fact_address"] = "address",
        ["fact_wifi"] = "Wi-Fi",
        ["fact_yes"] = "yes",
        ["fact_no"] = "no",
        ["fact_dbm"] = "{0} dBm",
        ["fact_memory"] = "memory",
        ["fact_memory_value"] = "{0} of {1} MB",
        ["fact_board_temp"] = "board temperature",
        ["fact_uptime"] = "up for",
        ["fact_air_sensor"] = "air sensor",
        ["fact_radar"] = "radar",
        ["fact_version"] = "version",
        ["fact_ok"] = "working",
        ["fact_silent"] = "silent",

        // ---------------------------------------------------------- weather
        ["wmo_0"] = "clear",
        ["wmo_1"] = "mostly clear",
        ["wmo_2"] = "partly cloudy",
        ["wmo_3"] = "overcast",
        ["wmo_fog"] = "fog",
        ["wmo_drizzle"] = "drizzle",
        ["wmo_rain"] = "rain",
        ["wmo_freezing"] = "freezing rain",
        ["wmo_snow"] = "snow",
        ["wmo_showers"] = "showers",
        ["wmo_snow_showers"] = "snow showers",
        ["wmo_storm"] = "thunderstorm",

        // ---------------------------------------------------------- screens
        ["screens_hint"] = "the checkbox turns a screen on; drag a row to change its place in the carousel",
        ["screens_apply"] = "Apply to device",
        ["screens_reload"] = "Reload",
        ["screens_off"] = "off",
        ["screens_saving"] = "saving…",
        ["screens_saved"] = "done — the device rebuilds its carousel itself",
        ["screens_moved"] = "order changed — press “Apply to device”",

        // ------------------------------------------------------- statistics
        ["stats_hint"] = "today, from the device's records",
        ["stats_at_desk"] = "AT THE DESK",
        ["stats_longest"] = "WITHOUT A BREAK",
        ["stats_keys"] = "KEYSTROKES",
        ["stats_clicks"] = "CLICKS",
        ["stats_by_hour"] = "BY HOUR",
        ["stats_by_category"] = "DOING WHAT",
        ["category_code"] = "code",
        ["category_browser"] = "browser",
        ["category_game"] = "games",
        ["category_other"] = "other",

        // ------------------------------------------------------------ radar
        ["radar_hint"] = "what the radar sees, and why the device thinks you are at the desk or not",
        ["radar_verdict_title"] = "NOW",
        ["radar_at_desk"] = "at the desk",
        ["radar_away"] = "desk is empty",
        ["radar_reason_motion_now"] = "motion near the desk right now",
        ["radar_reason_motion"] = "motion near the desk {0} ago",
        ["radar_reason_still"] = "no motion near the desk for {0}; the module still sees a target, and presence lasts {1} more at most",
        ["radar_reason_ghost"] = "no motion near the desk for {0}, while the radar still sees a target in the {1} zone — that is not someone at the desk",
        ["radar_reason_empty"] = "the radar sees no one",
        ["radar_reason_no_rule"] = "the near-desk rule is off: the device sent no zone thresholds, so the module decides alone",
        ["radar_fact_module"] = "the module itself",
        ["radar_fact_target"] = "sees a target",
        ["radar_fact_nobody"] = "nobody",
        ["radar_fact_distance"] = "target distance",
        ["radar_fact_quiet"] = "no motion near the desk",
        ["radar_cm"] = "{0} cm",
        ["radar_zones_title"] = "ZONES",
        ["radar_zone"] = "{0}–{1} cm",
        ["radar_near"] = "at the desk",
        ["radar_ignored"] = "ignored",
        ["radar_legend_moving"] = "motion",
        ["radar_legend_static"] = "still",
        ["radar_legend_threshold"] = "the tick is the trigger threshold",
        ["radar_how_title"] = "HOW IT WORKS",
        ["radar_how_1"] = "The 24 GHz radar splits distance into 75 cm zones and measures two signals in each: motion, and still presence — the breathing of someone sitting, for instance.",
        ["radar_how_2"] = "\"At the desk\" holds while there has been motion in the near zones, within one and a half metres. Far zones are needed to see a person sitting still, but without fresh motion near the desk they hold presence for three minutes at most.",
        ["radar_how_3"] = "If a far zone lights up while you are away, something is moving there: a curtain, a fan, a person behind a door. The radar sees through thin walls too.",
        ["radar_levels"] = "statistics for threshold calibration: {0:0.#} h",

        // --------------------------------------------------------- computer
        ["computer_hint"] = "what the app collects from this computer and sends to the device",
        ["computer_state_title"] = "DATA COLLECTION",
        ["computer_running"] = "sending to the device",
        ["computer_offline"] = "collecting, but the device does not answer",
        ["computer_starting"] = "starting…",
        ["computer_off"] = "off",
        ["computer_blocked"] = "not started — the old agent is in the way",
        ["computer_fact_board"] = "device",
        ["computer_fact_link"] = "connection",
        ["computer_fact_temps"] = "temperatures",
        ["computer_fact_input"] = "keystrokes",
        ["computer_fact_rights"] = "rights",
        ["computer_fact_window"] = "last window",
        ["computer_temps_ok"] = "readable",
        ["computer_temps_no"] = "no",
        ["computer_input_ok"] = "counted",
        ["computer_input_no"] = "not counted",
        ["computer_rights_admin"] = "administrator",
        ["computer_rights_user"] = "standard",
        ["computer_temps_hint"] = "Without administrator rights the CPU temperature cannot be read, and the GPU / CPU screen on the device stays incomplete. Enable autostart — it grants the rights without a prompt at every login.",
        ["computer_grant"] = "Enable autostart with rights",
        ["computer_last_error"] = "last error: {0}",
        ["computer_enabled"] = "Send data from this computer to the device",
        ["computer_enabled_note"] = "Keystrokes are only counted: which keys were pressed is neither seen nor stored. Turn this off and the device stops receiving data from this computer; everything else keeps working.",
        ["computer_old_agent"] = "The agent from the previous version is running, and it cannot be stopped without administrator rights. While it runs, collection here stays off: the two would keep knocking each other off the device. The button below sets up autostart with rights and removes the agent — Windows asks for confirmation once.",
        ["computer_old_agent_fix"] = "Set up autostart and remove the agent",
        ["computer_restarting"] = "restarting with rights…",
        ["computer_restart_failed"] = "autostart is set up, but restarting with rights failed — quit the app from the tray and open it again",
        ["computer_log_title"] = "LOG",
        ["computer_log_empty"] = "the log is empty",
        ["computer_log_open"] = "Open the full file",
        ["computer_probe_title"] = "DIAGNOSTICS",
        ["computer_probe_note"] = "What the app sees on this computer: which category it gives each window and which sensors it finds.",
        ["computer_probe_windows"] = "Windows and their categories",
        ["computer_probe_sensors"] = "Sensors",
        ["computer_probe_running"] = "looking…",
        ["probe_col_process"] = "process",
        ["probe_col_category"] = "category",
        ["probe_col_path"] = "path",
        ["probe_by_list"] = " (listed)",
        ["probe_no_path"] = "path not visible",
        ["probe_overrides_from"] = "overrides are read from {0}",
        ["probe_temps_ok"] = "temperatures are available",
        ["probe_temps_none"] = "no temperatures — administrator rights needed",
        ["probe_temps_blocked"] = "no temperatures even with rights — antivirus has probably blocked the sensor driver",
        ["log_start_admin"] = "collection started: broker {0}:{1}, with administrator rights",
        ["log_start_user"] = "collection started: broker {0}:{1}, without administrator rights",
        ["log_no_hooks"] = "could not install the input hooks — keystrokes will not be counted",
        ["log_connected"] = "connected to {0}:{1}",
        ["log_connect_failed"] = "cannot connect to {0}:{1} — {2}",
        ["log_local_names"] = ".local names resolve only about half the time from Windows — the app will look for the device on the network itself",
        ["log_no_temps"] = "temperature sensors are unavailable — administrator rights needed",
        ["log_stopped"] = "collection stopped",
        ["log_old_task_removed"] = "the old agent's task was removed",
        ["log_old_agent_stopped"] = "the old agent was stopped — the app does its job now",
        ["log_old_agent_alive"] = "the old agent runs with rights this app does not have — it could not be stopped",
        ["log_board_found"] = "device found on the network: {0}",
        ["log_autostart_moved"] = "the previous version's autostart was moved to a Scheduled Task — now with rights",

        // --------------------------------------------------------- settings
        ["settings_hint"] = "settings for this app, and the things easier to change with a mouse than on the device",
        ["host_title"] = "WHERE TO FIND THE DEVICE",
        ["host_test"] = "Test",
        ["host_note"] = "The address finds itself: if the device does not answer, the app looks for it on its network and remembers it as numbers. You can type it in too — for instance, if the device is on another subnet.",
        ["host_find"] = "Find on the network",
        ["host_finding"] = "looking for the device… {0} of {1}",
        ["host_found"] = "found: {0}",
        ["host_not_found"] = "not found on the network — check that the device is on and connected to the same network",
        ["host_testing"] = "testing…",
        ["host_bad"] = "no answer: {0}",
        ["host_good"] = "answers, version {0}",
        ["lang_title"] = "LANGUAGE",
        ["lang_note"] = "Changes the language of this window and of the device screen. Window titles, track names and city names stay as they are — that is other people's text, not our interface.",
        ["lang_device_now"] = "the device screen is in: {0}",
        ["lang_device_saving"] = "switching the device screen…",
        ["lang_device_offline"] = "the device is offline — its screen will switch when you pick the language again",
        ["city_title"] = "CITY FOR THE WEATHER",
        ["city_find"] = "Find",
        ["city_note"] = "Type a name and press “Find” — it searches every populated place on Earth, not a list of major cities.",
        ["city_apply"] = "Set on the device",
        ["city_unnamed"] = "{0:0.00}, {1:0.00} — no city name",
        ["city_too_short"] = "type at least two letters",
        ["city_searching"] = "searching…",
        ["city_nothing"] = "nothing found for “{0}”",
        ["city_one"] = "found one — check it and set it on the device",
        ["city_many"] = "found {0}: pick the right one, places share names",
        ["city_setting"] = "setting {0}…",
        ["city_done"] = "done — the device fetches the weather now, without waiting for its hour",
        ["city_no_link"] = "cannot reach the city search",
        ["touch_title"] = "TOUCH SENSITIVITY",
        ["touch_hard"] = "firm",
        ["touch_easy"] = "light",
        ["touch_note"] = "The device screen is resistive: it measures not a touch but how hard two layers press together. The slider sets how hard counts as a press — to the right means lighter. It applies at once; no reboot.",
        ["touch_note_safe"] = "Raising it is almost always safe: an untouched panel produces no false presses at any setting. If the screen starts pressing itself, move it left.",
        ["touch_very_hard"] = "firm press",
        ["touch_normal"] = "normal press",
        ["touch_light"] = "light press",
        ["touch_lightest"] = "lightest",
        ["touch_saving"] = "{0} — saving",
        ["touch_saved"] = "{0} — done, try pressing",
        ["calib_title"] = "TOUCH CALIBRATION",
        ["calib_note"] = "If presses land in the wrong place — you press the right edge and the middle responds — calibrate. A cross appears on the device screen: press its centre, then the next one. Four presses, no hurry — there is no countdown.",
        ["calib_start"] = "Start calibration",
        ["calib_starting"] = "starting…",
        ["calib_cancel"] = "Cancel",
        ["calib_waiting"] = "look at the device screen — press cross {0} of {1}",
        ["calib_done"] = "done — presses now land where they should",
        ["calib_cancelled"] = "calibration cancelled, the previous settings are kept",
        ["calib_failed"] = "failed: {0}",
        ["calib_no_service"] = "the device did not respond to calibration — it probably runs old code; update it with deploy.sh",
        ["startup_title"] = "STARTUP",
        ["startup_autostart"] = "Start with Windows",
        ["startup_minimized"] = "Start minimised to the tray",
        ["startup_note"] = "Autostart is a Scheduled Task with administrator rights: without them temperatures cannot be read. Turning it on asks for confirmation once; after that the app starts silently and waits for the device in the tray.",
        ["startup_stale"] = "autostart points to the program's old location — tick the box again",
        ["autostart_waiting"] = "waiting for Windows to confirm…",
        ["autostart_cancelled"] = "no confirmation — autostart unchanged",
        ["autostart_failed"] = "could not change autostart",
        ["backup_title"] = "DATABASE BACKUPS",
        ["backup_none"] = "no backups yet",
        ["backup_last"] = "last backup: {0:MM-dd HH:mm}",
        ["backup_failed"] = " · could not update: {0}",
        ["backup_running"] = "taking a backup…",
        ["backup_now"] = "Back up now",
        ["backup_open"] = "Open folder",
        ["backup_note"] = "The measurement history lives on the device's memory card in a single copy, and cards wear out. The app pulls the database once a day and keeps the last seven copies.",

        // ------------------------------------------------------------- time
        ["time_hm"] = "{0} h {1:00} m",
        ["time_m"] = "{0} m",
        ["uptime_dh"] = "{0} d {1} h",
        ["uptime_hm"] = "{0} h {1} min",
        ["uptime_m"] = "{0} min",
        ["ago_s"] = "{0} s",
        ["ago_m"] = "{0} min",
    };
}
