namespace DeskCompanion.Services;

/// <summary>English. Keys are the Russian table's; a missing one falls back to Russian.</summary>
public static partial class Strings
{
    public static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        // ------------------------------------------------------------ menu
        ["nav_overview"] = "Overview",
        ["nav_screens"] = "Screens",
        ["nav_stats"] = "Statistics",
        ["nav_agent"] = "Agent",
        ["nav_settings"] = "Settings",

        // ------------------------------------------------- device connection
        ["link_searching"] = "looking for the device",
        ["link_waiting"] = "waiting for the device",
        ["link_none"] = "no connection",
        ["link_ok"] = "device connected",
        ["tray_state"] = "Desk Companion — {0}",
        ["tray_air"] = "Desk Companion — CO₂ {0} ppm, {1}",
        ["tray_at_desk"] = "at the desk",
        ["tray_nobody"] = "nobody there",
        ["tray_open"] = "Open",
        ["tray_quit"] = "Quit",
        ["board_no_answer"] = "the device did not answer",
        ["board_timeout"] = "the device did not answer in time",
        ["board_no_host"] = "that address is not on the network",
        ["board_no_link"] = "cannot reach the device",
        ["board_status"] = "the device answered {0}",
        ["board_empty_file"] = "the device returned an empty file",
        ["not_saved"] = "not saved",

        // --------------------------------------------------------- overview
        ["overview_hint"] = "everything the device knows right now",
        ["card_air"] = "AIR",
        ["card_desk"] = "DESK",
        ["card_outside"] = "OUTSIDE",
        ["card_pc"] = "COMPUTER",
        ["card_board"] = "DEVICE",
        ["air_silent"] = "sensor is silent",
        ["air_caption"] = "{0:0.0} °C · humidity {1:0} %",
        ["desk_present"] = "here",
        ["desk_empty"] = "empty",
        ["radar_distance"] = "radar sees someone at {0} cm",
        ["radar_online"] = "radar connected",
        ["radar_silent"] = "radar is silent",
        ["weather_none"] = "no forecast",
        ["pc_no_window"] = "no active window",
        ["pc_offline"] = "the agent is offline — no data from this computer",
        ["pc_cpu"] = "processor",
        ["pc_cpu_temp"] = "its temperature",
        ["pc_gpu"] = "graphics card",
        ["pc_gpu_temp"] = "its temperature",
        ["fact_address"] = "address",
        ["fact_wifi"] = "Wi-Fi",
        ["fact_yes"] = "yes",
        ["fact_no"] = "no",
        ["fact_dbm"] = "{0} dBm",
        ["fact_memory"] = "memory",
        ["fact_memory_value"] = "{0} of {1} MB",
        ["fact_board_temp"] = "board temperature",
        ["fact_uptime"] = "up for",
        ["fact_air_sensor"] = "air sensor",
        ["fact_radar"] = "radar",
        ["fact_version"] = "version",
        ["fact_ok"] = "working",
        ["fact_silent"] = "silent",

        // ---------------------------------------------------------- weather
        ["wmo_0"] = "clear",
        ["wmo_1"] = "mostly clear",
        ["wmo_2"] = "partly cloudy",
        ["wmo_3"] = "overcast",
        ["wmo_fog"] = "fog",
        ["wmo_drizzle"] = "drizzle",
        ["wmo_rain"] = "rain",
        ["wmo_freezing"] = "freezing rain",
        ["wmo_snow"] = "snow",
        ["wmo_showers"] = "showers",
        ["wmo_snow_showers"] = "snow showers",
        ["wmo_storm"] = "thunderstorm",

        // ---------------------------------------------------------- screens
        ["screens_hint"] = "the checkbox turns a screen on; drag a row to change its place in the carousel",
        ["screens_apply"] = "Apply to device",
        ["screens_reload"] = "Reload",
        ["screens_off"] = "off",
        ["screens_saving"] = "saving…",
        ["screens_saved"] = "done — the device rebuilds its carousel itself",
        ["screens_moved"] = "order changed — press “Apply to device”",

        // ------------------------------------------------------- statistics
        ["stats_hint"] = "today, from the device's records",
        ["stats_at_desk"] = "AT THE DESK",
        ["stats_longest"] = "WITHOUT A BREAK",
        ["stats_keys"] = "KEYSTROKES",
        ["stats_clicks"] = "CLICKS",
        ["stats_by_hour"] = "BY HOUR",
        ["stats_by_category"] = "DOING WHAT",
        ["category_code"] = "code",
        ["category_browser"] = "browser",
        ["category_game"] = "games",
        ["category_other"] = "other",

        // ------------------------------------------------------------ agent
        ["agent_hint"] = "the program that collects data from this computer and sends it to the device",
        ["agent_state_title"] = "STATUS",
        ["agent_running"] = "running",
        ["agent_running_offline"] = "running, but cannot reach the device",
        ["agent_hung"] = "not responding",
        ["agent_hung_detail"] = "the process exists, but its last sign of life was {0} ago",
        ["agent_stopped"] = "stopped",
        ["agent_missing"] = "DeskAgent.exe not found — put it in the same folder as this app",
        ["agent_fact_board"] = "device",
        ["agent_fact_link"] = "connection",
        ["agent_fact_temps"] = "temperatures",
        ["agent_fact_input"] = "keystrokes",
        ["agent_fact_rights"] = "rights",
        ["agent_fact_started"] = "started",
        ["agent_temps_ok"] = "readable",
        ["agent_temps_no"] = "no",
        ["agent_input_ok"] = "counted",
        ["agent_input_no"] = "not counted",
        ["agent_rights_admin"] = "administrator",
        ["agent_rights_user"] = "standard",
        ["agent_temps_hint"] = "Without administrator rights the agent cannot read temperatures, and the GPU / CPU screen on the device stays empty. Start it with rights — or set up autostart, which grants them without a prompt.",
        ["agent_last_error"] = "last error: {0}",
        ["agent_start"] = "Start",
        ["agent_restart"] = "Restart",
        ["agent_stop"] = "Stop",
        ["agent_start_admin"] = "Start as administrator",
        ["agent_starting"] = "starting…",
        ["agent_stopping"] = "stopping…",
        ["agent_done"] = "done",
        ["agent_keep"] = "Keep the agent running",
        ["agent_keep_note"] = "If the agent closes or crashes, the app brings it back. “Stop” turns this off — otherwise a stopped agent would return at once.",
        ["agent_admin_cancelled"] = "start with rights cancelled",
        ["agent_failed"] = "did not start: {0}",
        ["agent_exited"] = "started and exited at once — see the log",
        ["agent_not_stopped"] = "did not stop — it probably runs with rights this app does not have",
        ["agent_autostart_title"] = "AUTOSTART",
        ["agent_autostart_on"] = "set up — the agent starts at login with administrator rights, without a prompt",
        ["agent_autostart_off"] = "not set up — the app will start the agent, but without administrator rights",
        ["agent_autostart_note"] = "The agent's autostart is a Scheduled Task: only a task grants administrator rights without a confirmation window at every login. To set it up or remove it, run pc\\autostart.ps1 as administrator.",
        ["agent_log_title"] = "LOG",
        ["agent_log_empty"] = "the log is empty — the agent has never run",
        ["agent_log_open"] = "Open the full file",
        ["agent_probe_title"] = "DIAGNOSTICS",
        ["agent_probe_note"] = "What the agent sees on this computer. Safe while the agent runs: it does not talk to the device and does not count keystrokes.",
        ["agent_probe_windows"] = "Windows and their categories",
        ["agent_probe_sensors"] = "Sensors",
        ["agent_probe_running"] = "looking…",
        ["agent_probe_timeout"] = "diagnostics did not answer within 30 seconds",

        // --------------------------------------------------------- settings
        ["settings_hint"] = "settings for this app, and the things easier to change with a mouse than on the device",
        ["host_title"] = "WHERE TO FIND THE DEVICE",
        ["host_test"] = "Test",
        ["host_note"] = "Names like deskpi.local resolve only about half the time from Windows — if there is no connection, enter the address as numbers; your router's web page shows it. The agent reads the address from here too.",
        ["host_testing"] = "testing…",
        ["host_bad"] = "no answer: {0}",
        ["host_good"] = "answers, version {0}",
        ["lang_title"] = "LANGUAGE",
        ["lang_note"] = "Changes the language of this window and of the device screen. Window titles, track names and city names stay as they are — that is other people's text, not our interface.",
        ["lang_device_now"] = "the device screen is in: {0}",
        ["lang_device_saving"] = "switching the device screen…",
        ["lang_device_offline"] = "the device is offline — its screen will switch when you pick the language again",
        ["city_title"] = "CITY FOR THE WEATHER",
        ["city_find"] = "Find",
        ["city_note"] = "Type a name and press “Find” — it searches every populated place on Earth, not a list of major cities.",
        ["city_apply"] = "Set on the device",
        ["city_unnamed"] = "{0:0.00}, {1:0.00} — no city name",
        ["city_too_short"] = "type at least two letters",
        ["city_searching"] = "searching…",
        ["city_nothing"] = "nothing found for “{0}”",
        ["city_one"] = "found one — check it and set it on the device",
        ["city_many"] = "found {0}: pick the right one, places share names",
        ["city_setting"] = "setting {0}…",
        ["city_done"] = "done — the device fetches the weather now, without waiting for its hour",
        ["city_no_link"] = "cannot reach the city search",
        ["touch_title"] = "TOUCH SENSITIVITY",
        ["touch_hard"] = "firm",
        ["touch_easy"] = "light",
        ["touch_note"] = "The device screen is resistive: it measures not a touch but how hard two layers press together. The slider sets how hard counts as a press — to the right means lighter. It applies at once; no reboot.",
        ["touch_note_safe"] = "Raising it is almost always safe: an untouched panel produces no false presses at any setting. If the screen starts pressing itself, move it left.",
        ["touch_very_hard"] = "firm press",
        ["touch_normal"] = "normal press",
        ["touch_light"] = "light press",
        ["touch_lightest"] = "lightest",
        ["touch_saving"] = "{0} — saving",
        ["touch_saved"] = "{0} — done, try pressing",
        ["calib_title"] = "TOUCH CALIBRATION",
        ["calib_note"] = "If presses land in the wrong place — you press the right edge and the middle responds — calibrate. A cross appears on the device screen: press its centre, then the next one. Four presses, no hurry — there is no countdown.",
        ["calib_start"] = "Start calibration",
        ["calib_cancel"] = "Cancel",
        ["calib_waiting"] = "look at the device screen — press cross {0} of {1}",
        ["calib_done"] = "done — presses now land where they should",
        ["calib_cancelled"] = "calibration cancelled, the previous settings are kept",
        ["calib_failed"] = "failed: {0}",
        ["calib_no_service"] = "the device did not respond to calibration — it probably runs old code; update it with deploy.sh",
        ["startup_title"] = "STARTUP",
        ["startup_autostart"] = "Start with Windows",
        ["startup_minimized"] = "Start minimised to the tray",
        ["startup_note"] = "The app waits for the device by itself: while the device is offline, it sits quietly in the tray and connects as soon as it appears.",
        ["startup_failed"] = "could not change autostart",
        ["backup_title"] = "DATABASE BACKUPS",
        ["backup_none"] = "no backups yet",
        ["backup_last"] = "last backup: {0:MM-dd HH:mm}",
        ["backup_failed"] = " · could not update: {0}",
        ["backup_running"] = "taking a backup…",
        ["backup_now"] = "Back up now",
        ["backup_open"] = "Open folder",
        ["backup_note"] = "The measurement history lives on the device's memory card in a single copy, and cards wear out. The app pulls the database once a day and keeps the last seven copies.",

        // ------------------------------------------------------------- time
        ["time_hm"] = "{0} h {1:00} m",
        ["time_m"] = "{0} m",
        ["uptime_dh"] = "{0} d {1} h",
        ["uptime_hm"] = "{0} h {1} min",
        ["uptime_m"] = "{0} min",
        ["ago_s"] = "{0} s",
        ["ago_m"] = "{0} min",
    };
}
